name: swift_aid
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  scroll_wheel_date_picker: ^0.0.2+1
  cupertino_height_picker: ^1.0.0
  animated_weight_picker: ^1.0.3
  shared_preferences: ^2.3.5
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  fluttertoast: ^8.2.10
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  http_parser: ^4.1.2
  http: ^1.2.2






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  