name: swift_aid
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  scroll_wheel_date_picker: ^0.0.2+1
  cupertino_height_picker: ^1.0.0
  animated_weight_picker: ^1.0.3
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1
  mapbox_maps_flutter: ^2.5.1
  shared_preferences: ^2.3.5
  custom_info_window: ^1.0.1
  firebase_database: ^11.3.1
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  audio_waveforms: ^1.3.0
  table_calendar: ^3.2.0
  firebase_core: ^3.10.0
  google_sign_in: ^6.2.2
  flutter_sound: ^9.28.0
  firebase_auth: ^5.4.0
  fluttertoast: ^8.2.10
  path_provider: ^2.1.2
  flutter_bloc: ^9.0.0
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  http_parser: ^4.1.2
  just_audio: ^0.10.0
  avatar_glow: ^3.0.1
  geocoding: ^3.0.0
  record: ^5.0.1
  http: ^1.2.2
  uuid: ^4.4.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/maptheme/silver_theme.json
    - assets/maptheme/retro_theme.json
    - assets/maptheme/night_theme.json

  