// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhizzaqoadg-WL9WcbbWQngsO2LpGoylI',
    appId: '1:553469458906:web:a9f69a6ee236805aaf28e3',
    messagingSenderId: '553469458906',
    projectId: 'swift-aid-fyp',
    authDomain: 'swift-aid-fyp.firebaseapp.com',
    databaseURL: 'https://swift-aid-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'swift-aid-fyp.firebasestorage.app',
    measurementId: 'G-6QGQZ11NLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mVDHdECXBMlHqHFaAoWUmnuUpuEvvDs',
    appId: '1:553469458906:android:25ade0e992ad19caaf28e3',
    messagingSenderId: '553469458906',
    projectId: 'swift-aid-fyp',
    databaseURL: 'https://swift-aid-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'swift-aid-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRffsDJ_U4Gp7hwx9eUMUMmtkTOTenKpA',
    appId: '1:553469458906:ios:797ba6429f8272c5af28e3',
    messagingSenderId: '553469458906',
    projectId: 'swift-aid-fyp',
    databaseURL: 'https://swift-aid-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'swift-aid-fyp.firebasestorage.app',
    androidClientId: '553469458906-t5ekfeskj6v026fojvcn3dvm0jgam1j6.apps.googleusercontent.com',
    iosClientId: '553469458906-8ckftqrun7u9r0c97qu0d1ufs5nj34et.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRffsDJ_U4Gp7hwx9eUMUMmtkTOTenKpA',
    appId: '1:553469458906:ios:797ba6429f8272c5af28e3',
    messagingSenderId: '553469458906',
    projectId: 'swift-aid-fyp',
    databaseURL: 'https://swift-aid-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'swift-aid-fyp.firebasestorage.app',
    androidClientId: '553469458906-t5ekfeskj6v026fojvcn3dvm0jgam1j6.apps.googleusercontent.com',
    iosClientId: '553469458906-8ckftqrun7u9r0c97qu0d1ufs5nj34et.apps.googleusercontent.com',
    iosBundleId: 'com.example.swiftAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhizzaqoadg-WL9WcbbWQngsO2LpGoylI',
    appId: '1:553469458906:web:c716282de75dc6f8af28e3',
    messagingSenderId: '553469458906',
    projectId: 'swift-aid-fyp',
    authDomain: 'swift-aid-fyp.firebaseapp.com',
    databaseURL: 'https://swift-aid-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'swift-aid-fyp.firebasestorage.app',
    measurementId: 'G-M3P3P2D0DW',
  );

}